config.debug.allow.cors: true

spring.datasource:
  url: jdbc:h2:tcp://localhost/~/ftm
  username: ftmUser
  password: ftm
  driver-class-name:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: classpath*:/mybatis/*Mapper.xml
